In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/tb_lobby_stats_player.csv")

In [4]:
df.head()

,idLobbyGame,idPlayer,idRoom,qtKill,qtAssist,qtDeath,qtHs,qtBombeDefuse,qtBombePlant,qtTk,...,qtFlashAssist,qtHitHeadshot,qtHitChest,qtHitStomach,qtHitLeftAtm,qtHitRightArm,qtHitLeftLeg,qtHitRightLeg,flWinner,dtCreatedAt
0,1,1,1,5,1,16,2,0,0,0.0,...,0.0,3.0,13.0,4.0,2.0,2.0,1.0,0.0,0,2022-01-21 19:45:44
1,2,1,2,24,3,18,6,0,4,0.0,...,0.0,7.0,26.0,14.0,2.0,1.0,1.0,3.0,1,2022-02-04 02:09:47
2,3,2,3,6,4,23,2,0,1,0.0,...,0.0,3.0,15.0,8.0,1.0,2.0,0.0,2.0,0,2021-09-18 18:07:43
3,3,391,27508,10,5,20,4,1,0,0.0,...,0.0,6.0,27.0,10.0,1.0,7.0,6.0,6.0,1,2021-09-18 18:07:43
4,4,2,4,8,4,26,6,0,2,0.0,...,2.0,8.0,19.0,12.0,2.0,3.0,2.0,5.0,0,2021-09-27 00:17:45

In [13]:
df["idPlayer"].value_counts(ascending=True)

2622      1
8         1
2521      1
2646      1
1190      1
       ...
1335    625
20      666
2289    677
1663    746
1922    873
Name: idPlayer, Length: 2469, dtype: int64

In [17]:
df["descMapName"].value_counts(normalize=True)

de_mirage      0.315506
de_inferno     0.228469
de_dust2       0.129426
de_vertigo     0.108193
de_overpass    0.076502
de_nuke        0.076312
de_train       0.042606
de_ancient     0.022986
Name: descMapName, dtype: float64